import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ReactQueryProvider } from "@/components/providers/ReactQueryProvider";
import { AuthSessionProvider } from "@/features/auth/components/AuthSessionProvider";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Buddy Script",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo-copy.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground font-sans antialiased overflow-y-scroll overscroll-auto [&::-webkit-scrollbar]:hidden">
        <ReactQueryProvider>
          <AuthSessionProvider>{children}</AuthSessionProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
